---

- name: "configuration play." 
  hosts: ec2-3-19-232-220.us-east-2.compute.amazonaws.com
  user: ubuntu
  gather_facts: false

  pre_tasks:
    - name: "wait 60 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 20
        timeout: 60

    - name: "install python for Ansible"
      become: true
      shell: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    # Your code here
    - configure-server
    - configure-prometheus-node-exporter

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
   